### ISSUE TITLE
Plugin does not recognize the credential and apihost in manifest file.

### ISSUE THREAD

**Issue by style95** [naver/openwhisk-intellij-plugin#20]
If a user already specified `apihost` and `credentials`, I think the plugin should deploy entities based on it.
It would be great to open a confirmation popup.
```
project:
  namespace: myNamespace
  credential: 50c9ec21-2d31-4e7d-83fc-cfc3d955215d:OxfL69AgDRryMCxnMYNRPv4u1EgaVAFNaYX8iXureMJG7mBjQEFzZdlkxzjkkl32
  apiHost: openwhisk.com
```
